- hosts: all
  become: true
  roles:
    - common

- hosts: master
  become: true
  roles:
    - master

- hosts: worker
  become: true
  roles:
    - worker

- hosts: networking
  become: true
  roles:
    - networking
